### ISSUE TITLE
Small UI disappearing bug on GameUI module

### ISSUE THREAD

**Issue by MadCatMKII** [psiberx/cp2077-cet-kit#6]
I might have found a small bug related to the GameUI module. 
It's easy to reproduce, but a bit hard to spot if you didn't know what are you looking for.

Steps to reproduce it:
- Install CET and GameUI-WhereAmI
- Load a saved game
- Fix your aim over a scannable object which you can interact (radios, floodlights, etc.)
- Then toggle the scanning two or three times without move the cursor
- Some UI elements (like the minimap) should hide until you move the cursor and try to scan other object

I tested this behavior with and without the module installed, and seems it manifests only when the module is present.

![Scanning UI bug](https://github.com/user-attachments/assets/1b34d350-04be-4c6f-957b-f1ecaa7145e4)

**Comment by psiberx** [comment]
Is it reproducible with just GameUI events listener, but not WhereAmI demo?

**Comment by MadCatMKII** [comment]
I notice on my mod and WhereAmI. So should require GameUI being called by other mods.

**Comment by psiberx** [comment]
I tried it with WhereAmI, but can't reproduce. The minimap and other elements always hide and come back as expected.

**Comment by MadCatMKII** [comment]
Ok. I thought uninstall the other mods with vortex would be enough. I'm going to run a repair in my game installation to ensure a clean environment.
Maybe it's been caused by other factors.

**Comment by MadCatMKII** [comment]
Curious. Looks like a game bug specifically related to that area on the video I attached to the issue. It happens only on that area and a minor activity spawned there before I stumble on this bug. Looks like it may happen in other places, but now we know why.
Anyway, sorry to take your time with this @psiberx . 
At least we know it's something which don't require a fix, and I can explain to the players affected the best way to deal with it.
